### ISSUE TITLE
Click listeners on RecyclerView

### ISSUE THREAD

**Issue by efung** [codepath/android_guides#104]
In the example showing how to bubble up clicks to the parent, the static inner class for the view holder references a (non-static) instance variable from the Adapter.

**Comment by dstd** [comment]
@nesquena with this commit ([16e241f. Updated Using the RecyclerView](https://github.com/codepath/android_guides/wiki/Using-the-RecyclerView/_compare/f61f7e0a088979a15130c50ba6b977f9fa29c3f7...16e241f64ffa7ec9d2da6e3e5b4d4f7a74a9fcfa)) all ContactsAdapter instances now have a same listener, due to static `listener` field.

Wouldn't it be better just throw away both `static` modifiers –  from `listener` field and from `ViewHolder` class?
