### ISSUE TITLE
When using remote_id, ActiveAndroid use getID() or remote_id to do identifier?

### ISSUE THREAD

**Issue by kenneth2008** [codepath/android_guides#115]
When using remote_id, ActiveAndroid use getID() or remote_id to do identifier?

If ActiveAndroid using getID, can I get the correct parent by using where remote_id = 1?

**Comment by astuter** [comment]
ActiveAndroid uses `getId()` to retrieve value of primary key as it uses `Id`, instead of `_id` for column name by default.  Check here: https://github.com/pardom/ActiveAndroid/wiki/Pre-populated-databases

Thus if you have not provided your own primary key column in table,  `Id` and `remote_id` will be treated as separate identifier. 

So using `getId()`
`new Select().from(Item.class).where("Category = ?", Category.getId()).execute();`
and `remote_id`
`new Select().from(Item.class).where("Category = ?", Category.remote_id).execute();`
will give different result.

**Comment by kenneth2008** [comment]
Although I think get (Account object) which is a (variable of Employee) , ( Object Oriented)
Can I say it is reliable? It is not building relation by the original remote_id.
