### ISSUE TITLE
The chat tutorial with Parse is toxic.

### ISSUE THREAD

**Issue by Seichis** [codepath/android_guides#123]
Besides that it does not work the code and the walk through are like someone tried to create it. Did not have time to complete it and just left it there hanging. No hard feelings but certainly a waste of my time.
Cheers!

**Comment by nesquena** [comment]
Sorry you didn't find it helpful. The tutorial definitely works or has worked in the past. We've run hundreds of people through it successfully. Do you want to expand on "does not work" so that we may be able to fix it if there's an issue?

**Comment by appoll** [comment]
It was actually the best if not only resource I could get my hands on when getting started with Parse. However, try to be more eloquent and provide more information about the issues you are having.

**Comment by Seichis** [comment]
It does not register the ParseObject on Parse. The Message class (should be named something else imho, since android already has a Message class but not a real issue). There should also be a constructor in this class in order to work (at least now). 
The Listview, the list of messages and the adapter in the ChatActivity.class are just declared as it seems in the tutorial. 
Not catching the exception of no messages when doing the query for posts so it crashes if there is no message returned by the query. The postDelayed method of the Handler is used inside the runnable to post it and also inside onCreate (probably added from a version that worked) . 
Sorry for not explaining my frustration and sorry about my frustration in the first place but I needed something to start up quickly so not your fault anyway. It just seemed a perfect tutorial and got my hopes up and then I needed to debug it and eventually the way to handle the message transaction seems to be very expensive that way. Maybe using Parse Push would be the solution or using Pubnub  (https://www.pubnub.com/)  along with Parse for the message transaction.

**Comment by nesquena** [comment]
> It does not register the ParseObject on Parse. The Message class (should be named something else imho, since android already has a Message class but not a real issue). 

It's registered here: http://guides.codepath.com/android/Building-Simple-Chat-Client-with-Parse#8-create-model-class. The packages in Java means overlapping class names aren't an issue as you mentioned. 

> The postDelayed method of the Handler is used inside the runnable to post it and also inside onCreate (probably added from a version that worked) . 

That's intentional to cause it to poll repeatedly. It's supposed to be in both places. See https://guides.codepath.com/android/Repeating-Periodic-Tasks#execute-recurring-code-with-specified-interval

> Maybe using Parse Push would be the solution or using Pubnub (https://www.pubnub.com/) along with Parse for the message transaction.

See http://guides.codepath.com/android/Real-time-Messaging for links to getting started with pubnub. Of course a more complete version of the tutorial would use push rather than polling. The tutorial is meant to be a basic intro to how to use Parse including how to query and insert data. Not intended as a production-ready chat. 

> Sorry for not explaining my frustration and sorry about my frustration in the first place but I needed something to start up quickly so not your fault anyway. It just seemed a perfect tutorial and got my hopes up

No problem. Wish you the best. If you want to put together an alternate tutorial on the wiki that you think is better, I'd appreciate that. It's an open-source project for exactly that reason, so the community can help us make the guides as high quality as possible.

**Comment by Seichis** [comment]
Thank you for your feedback! Wish you the best too!
