### ISSUE TITLE
Otto deprecated

### ISSUE THREAD

**Issue by chug2k** [codepath/android_guides#151]
https://github.com/codepath/android_guides/wiki/Communicating-with-an-Event-Bus recommends Otto, but according to https://github.com/square/otto, the project's been deprecated in favor of RXJava/RXAndroid.

Likely related to #109

**Comment by nesquena** [comment]
We have the beginning of an [RxJava](http://guides.codepath.com/android/RxJava) guide here as well. Maybe we should add a note to the event bus guide, that Otto is deprecated? RxAndroid is the way I think the world is moving even though there is this [still somewhat maintained alternative](https://github.com/greenrobot/EventBus).

**Comment by nesquena** [comment]
cc @rogerhu

**Comment by rogerhu** [comment]
I looked at the approach with RxJava/RxAndroid (http://nerds.weddingpartyapp.com/tech/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/) and feel it's a step backwards.  You have to do a bunch of instance checks on the bus and decide what to do.  

EventBus 3.0 has gone the way of annotation libraries and seems to vastly have done better in the way of perf (http://nerds.weddingpartyapp.com/tech/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/). In fact it's far easier to use than Otto because it provides annotations for handling messages posted on a separate thread.

**Comment by rogerhu** [comment]
Update guides already to use EventBus library now.  Take a look.

**Comment by nesquena** [comment]
Great, thanks! I agree RXJava is heavier weight than a simple event bus mechanism.

**Comment by mikolasw** [comment]
can anybody share with me some good example of RxAndroid please?

**Comment by dionesxxx** [comment]
http://reactivex.io/tutorials.html @mikolasw

**Comment by rogerhu** [comment]
The reference from Otto is at http://nerds.weddingpartyapp.com/tech/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/.  It basically entails using a `PublishSubject` object of a generic type and emitting it from there.  Any subscribers downstream need to decode and do an instanceof check.

**Comment by anaselhajjaji** [comment]
@mikolasw
https://github.com/anaselhajjaji/android-samples/tree/master/RxAndroidSample

**Comment by RobLewis** [comment]
@rogerhu …or use multiple `PublishSubject`s. Which may violate the spirit of a "bus" but may also result in a cleaner and less confusing implementation, with no need for `instanceOf` checks.

**Comment by mirzaadil** [comment]
RxJava is best
