### ISSUE TITLE
Calling the individual classes in MainActivity

### ISSUE THREAD

**Issue by naatogmagithub** [codepath/android_guides#153]
Please as a beginner android, I'm confused as to how to link those classes written with the main activity. Will I need to call some specific methods too when  calling the RegistrationIntentService class in the main activity?
Thanks

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.
