### ISSUE TITLE
Circular Image to Square Image

### ISSUE THREAD

**Issue by dgngulcan** [codepath/android_guides#155]
Is it possible to make view transition also morph the view at the same time?

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.
