### ISSUE TITLE
Hi, when i read others' code , i find somewhere confusing.

### ISSUE THREAD

**Issue by cuikangyuan** [codepath/android_guides#157]
In general , in a component interface , we set @Component(dependencies = xxxComponent.class), it is about the  A component depends on B component
but if we set @Component(dependencies = xxxModule.class),  is it same to set @Component(modules = xxxModule.class) ?
if different ,  what the difference is between these two way?

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/).
