### ISSUE TITLE
What else is required apart from following steps on heroku after clicking on button? Does it require something else after the app is deployed and we get manage app and view options?

### ISSUE THREAD

**Issue by saurabhkhare2004** [codepath/android_guides#158]
Hi,

What else is required apart from following steps on heroku after clicking on button? Does it require something else after the app is deployed and we get manage app and view options?

I am getting 200, 404 and 403 error codes from browser as mentioned by heroku team. Am I missing any steps? Why is it showing unauthorized error? If this is the right message, how to get out of this?

Regards

Saurabh Khare

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.
