### ISSUE TITLE
DividerItemDecoration not moving while scrolling to new items

### ISSUE THREAD

**Issue by greysome** [codepath/android_guides#160]
I've been following the tutorial at [https://github.com/codepath/android_guides/wiki/Using-the-RecyclerView](url) and noticed something weird about the dividers. Whenever I create a new item and the RecyclerView automatically scrolls to the bottom, the divider does not move while the items "shift" above. The dividers are moving accordingly when I manually scroll up and down though.

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.
