### ISSUE TITLE
Ask - runtime permission libraray

### ISSUE THREAD

**Issue by 00ec454** [codepath/android_guides#163]
Library to implement runtime permission marshmallow and above 
https://github.com/00ec454/Ask

**Comment by nesquena** [comment]
See [here](http://guides.codepath.com/android/Managing-Runtime-Permissions-with-PermissionsDispatcher). You are more than welcome to document that library linked as well but closing this for now since we have a similar topic already documented [with a popular library](https://github.com/hotchemi/PermissionsDispatcher).
