### ISSUE TITLE
Google Play Services Crashing Genymotion 2.71 Samsung S6 Emulator 6.0.0

### ISSUE THREAD

**Issue by justdan0227** [codepath/android_guides#182]
Anyone else get the Samsung Galaxy S6 6.0.0 API 23 emulator working with Google Play Services. I've tried the install several times and keep getting Google Play Services has Stopped.   I have 5.0.0 working for some time now but wanted to add 6.0.0 and having issues. Using same ARM Translation Installer v1.1 for both 5.0.0 and 6.0.0 emulators and then the https://www.androidfilehost.com/?fid=24052804347835438 for the Android 6.0 as listed here.

Thoughts?

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.

**Comment by justdan0227** [comment]
I so sorry.  I thought the readme said "Our goal is to become the central crowdsourced resource for complete and up-to-date Android content and tutorials".  

I thought that gettingGoogle Play Services to run would be part of the complete and update-to-date Android Content.  Again my applogies.

**Comment by rogerhu** [comment]
There are numerous articles out there that explain how to get this to work (i.e. https://z3ntu.github.io/2015/12/10/play-services-with-genymotion.html).  It turns out there are two different files you have to flash to get this to work  (updated here https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support).   

The only way the Wiki works is if people who encounter it help us figure this stuff out and update the doc.
