### ISSUE TITLE
Each slide will new a fragment?

### ISSUE THREAD

**Issue by LeoYe168** [codepath/android_guides#185]
the code in you project
.....................
   @Override
    public Fragment getItem(int position) {
        return PageFragment.newInstance(position + 1);
    }
and .............
   public static PageFragment newInstance(int page) {
        Bundle args = new Bundle();
        args.putInt(ARG_PAGE, page);
        PageFragment fragment = new PageFragment();
        fragment.setArguments(args);
        return fragment;
    }

...so each tablayout switch will new a fragment,so will have many fragment Objects ？

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.
