### ISSUE TITLE
Fragment Navigation Drawer- Error while executing the code.

### ISSUE THREAD

**Issue by arunk11** [codepath/android_guides#191]
The app crashes, error: Main activity must implement onFragmentInteractionListener.

**Comment by nesquena** [comment]
The issues tab isn't really a place for these types of technical troubleshooting questions. You can [post here if you'd like](https://groups.google.com/forum/#!forum/codepath-android-guides) and if anyone wants to help then they can respond there. Otherwise, you would likely find more luck posting on [stackoverflow](http://stackoverflow.com/). Thanks for your understanding.

If you do fix this issue, let us know about it so we can make updates to the guide if needed. Thanks for the report.
