### ISSUE TITLE
Remove subjective writing from the wiki

### ISSUE THREAD

**Issue by jmitchell38488** [codepath/android_guides#241]
To start a suggestion with a subjective point of view is perhaps ironic, but necessary. I don't think that subjective writing is particularly helpful with guides, especially for newer developers. It tends to lead their thinking, analysis and points of view. Even senior developers can get caught up in subjective assertions.

This isn't a gripe about any particular editor or contributor, but more of a suggested wiki style guide that might help make information clearer, easier to understand, comprehend and overall better.

For example: `Android Studio by default will not recognize a lot of generated Dagger 2 code as legitimate classes` - Why? What about a reference? What constitutes _a lot_, is it 1 file or all of them?

Many how-to guides and tutorials are authored in the first person with interpretations and observations mixed in. If presented objectively as here are the facts, this is what works, you shouldn't do this because of XYZ - here, check out PSR on PHP for example etc. so forth, information memorization is typically more efficient and easier to process than content that's littered with inconsistencies, personal assertions and inaccuracies.

**Comment by rogerhu** [comment]
Thanks for the suggestion.  If you are using the guides, especially like the Dagger 2, feel free to propose changes. (see https://github.com/codepath/android_guides/wiki/Contributing-Guidelines).  Interpretations are part of trying to provide best practices and not necessarily trying to being subjective.  In the case you noted above, the reason is Java annotated classes that generated by the annotation process are not included in the classpath (see https://bitbucket.org/hvisser/android-apt).  

We can update that section but the guides can only get better with community support.

**Comment by jmitchell38488** [comment]
>  In the case you noted above, the reason is Java annotated classes that generated by the annotation process are not included in the classpath (see https://bitbucket.org/hvisser/android-apt).

Perfect, exactly the type of change I'm recommending. I'll make recommendations and propose necessary edits.
