### ISSUE TITLE
Creating and Animated Gif guide

### ISSUE THREAD

**Issue by geocohn** [codepath/android_guides#242]
I put together a [guide](https://hackmd.io/s/HJMrF3SVe) for creating app walkthroughs using only Android Studio plus a pair of standard _foss_ desktop apps. It's particularly useful on Linux platforms, where other conversion apps might not be available.

Please let me know a) if it's useful, and b) what tuneups it needs. Don't be shy, I'm very thick skinned!

**Comment by nesquena** [comment]
I appreciate this guide although I don't think it's appropriate for these Android guides since its such a specific usecase for this course and overlaps [with this guide](http://guides.codepath.com/android/Recording-Video-of-an-Android-Device) otherwise. Instead, I've added a link to your hackmd to the instructions for recording for the course so future participants can make use!
