### ISSUE TITLE
Add Espresso Testing Guide

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#34]
Add a guide outlining how to use espresso /cc @boes-matt

* [Robotium vs Espresso](https://docs.google.com/presentation/d/10Y9wGn1tgIasq6DqG30Qz27KJlndZAoHX1KI41aNkdM/edit#slide=id.g2a03d18b6_085)
* https://code.google.com/p/android-test-kit/wiki/EspressoStartGuide
* https://code.google.com/p/android-test-kit/wiki/Espresso
* https://code.google.com/p/android-test-kit/wiki/Espresso#Espresso_Setup_Instructions
* https://github.com/boes-matt/TestProject

**Comment by rogerhu** [comment]
You've looked at https://github.com/googlesamples/android-testing  right?  It's the most comprehensive Espresso walkthrough that Google provides.

**Comment by appoll** [comment]
Yes i did and I'm aware of many other resources as well. The problem is I'm
still lacking the guts to actually wrap up my drafts.

Sample projects are all setup and ready (for a while now), but it's
apparently harder than anticipated to find the right words and to give it
the codepath flavor I had in mind when I started. I'm probably only
overthinking it.

**Comment by rogerhu** [comment]
Yeah you're likely overthinking it....the 1st draft is obviously the
hardest.  Also it should be the crappiest.  :)  If you want to get
something started I am sure we can all help fill in the blanks.

**Comment by nesquena** [comment]
https://github.com/codepath/android_guides/wiki/UI-Testing-with-Espresso
