### ISSUE TITLE
Passing data to ParentFragment from 2nd child fragment of the parent fragment where the intermediate childfragment1 is dismissed.

### ISSUE THREAD

**Issue by safalspiff** [codepath/android_guides#355]
I have a parentFragment which opens a childFragment1(extends dialog fragment). From childFragment1 again I open another childfragment2(extends dialogFragment) and dismiss the childFragment1. I want to pass the data to parentFragment from ChildFragment2.

I tried opening the childfragment one like this by setting the targetFragment as ParentFragment but on doing so there is an error saying that "Setting target fragment to itself create a target cycle""

How do I solve the issue?

**Comment by kamiljeglikowski** [comment]
@safalspiff I think that you could mess something, because this should works like a charm:

When you are starting **child1** from **parent**, you should on the child1 setTargetFragment(parent)
https://developer.android.com/reference/android/app/Fragment.html#setTargetFragment(android.app.Fragment,%20int)

then when you are starting **child2** from **child1** you should setTargetFragment(getTargetFragment()...) 
getTargetFragment() in this moment with give you the **parent** fragment

Then when you will want to give something from **child2** to **parent** you will have to do something like

`                    if (getTargetFragment() != null) {
                        getTargetFragment().onActivityResult(getTargetRequestCode(), RESULT_OK, null);
                    }
`

And when will you implement onActivityResult in the **parent** fragment, you should be able to receive the data

**Comment by safall** [comment]
@kamiljeglikowski yeah i missed something. Solved it. Thanks :-)

**Comment by safalspiff** [comment]
@kamiljeglikowski Yeah solved it. I missed something. Thanks :-)
