### ISSUE TITLE
Fragment & FragmentStack management

### ISSUE THREAD

**Issue by lduparc** [codepath/android_guides#93]
Consider an Activity with a NavigationDrawer and a list of fragments. Using the drawer I can navigate to each fragment but in order to build a responsive and powerful application I have to : 

* Manage transitions between fragments
* Do not instantiate every time a fragment but use an existing one if possible
* Manage fragment state and its data
* Working with `AppCompatActivity` and `OptionsMenu` (Backpressed & Toolbar back button/Title)

Perform an Android application working with fragments implies to manage a lot of things. 
Would be great to have a guide for this. 

I'm not asking for a sample, but for a documentation who explain how to implement this as best as possible.

Improve the NavigationDrawer part with these cases could be great.

**Comment by rogerhu** [comment]
1) Navigating between fragments - http://guides.codepath.com/android/Creating-and-Using-Fragments#navigating-between-fragments

2) It's dangerous to keep references to fragments since they have their own lifecycle (i.e. if you hold onto a reference and replace a fragment with another, that old reference may cause memory leaks)

3) Fragment states & data --> I am starting to be of the opinion they are better managed as singleton instances via Dagger than trying to use Icepick to store them (does anyone else have opinions?)

4) See http://guides.codepath.com/android/Creating-and-Using-Fragments#actionbar-menu-items-and-fragments

**Comment by rogerhu** [comment]
FYI -- about #2, you can also do show/hide as discussed in http://guides.codepath.com/android/Creating-and-Using-Fragments#fragment-hiding-vs-replace.

In general I think this guide covers a lot about the ins/outs of fragments.

**Comment by aman007jham** [comment]
https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout
Can any one tell me how to customize the tabindicator i need image instead of line.Is it possible to customize
